### ISSUE TITLE
Edit Proposal :: renders html instead of markdown 

### ISSUE THREAD

**Issue by p00j4** [rubycentral/cfp-app#121]
```Meta
Feature: https://cfp.githubapp.com/events/  -> Edit proposal
```
**Actual** On click on Edit the submitted proposal, the content is rendered as HTML rather than markdown hence the length exceeds to save (even without editing anything because of additional html tags). 
The submitter is left with copying->externally convert into MD->Edit and paste here.
And then as well, the formatting may change as each external editors have slight different logic.
Can produce screen-shots if required. 

**Expected** We need the original submitted markdown style content to be rendered on Edit.

Not very sure if this needs be raised under [front-proposals](https://github.com/cfpio/front-proposals/)  or [callForPaper](https://github.com/cfpio/callForPapers/)

**Comment by mghaught** [comment]
Could you use the new version of the CFP App and see if this is still an issue.  Many things have been improved with the current version from when you submitted this issue.

**Comment by barrettclark** [comment]
This appears to be working. The markdown is shown in the edit textfields, so you would enter it the same in edit mode as in create mode.
