### ISSUE TITLE
Multiple Speakers for call for proposal and talks

### ISSUE THREAD

**Issue by MasseGuillaume** [rubycentral/cfp-app#124]
Sometimes there is more than one speaker for a CFP/talk.

/cc @heathermiller

**Comment by mghaught** [comment]
The newly merged version of the CFP App allows a speaker to invite other speakers to the same talk.  Does that satisfy what you were looking for?

**Comment by barrettclark** [comment]
The ability to invite other speakers works well. I'm closing this issue.
