### ISSUE TITLE
Same call for proposal for multiple events

### ISSUE THREAD

**Issue by MasseGuillaume** [rubycentral/cfp-app#125]
For example, at ScalaDays 2017 we had two locations: Chicago and Copenhagen. A speaker could do a CFP for multiple events.

/cc @heathermiller

**Comment by mghaught** [comment]
I apologize for not responding sooner.  What you're requesting is that someone could submit the same talk to both locations?  

Assuming I understand the request, the current app could not easily support this.  My recommendation would be to make two events and simply have speakers submit to each event.
