### ISSUE TITLE
App update since 2016

### ISSUE THREAD

**Issue by louisdorard** [rubycentral/cfp-app#128]
Hi there!

We’ve been using the CfP app for our own CfP for a couple of years now, and I’m noticing that there has been updates on the [Railsconf CfP](http://cfp.rubycentral.org/events/railsconf2018). Do you have any plans to open source those updates?

Many thanks,

Louis

**Comment by myabc** [comment]
@louisdorard The latest changes from the original team behind the CFP app can be found at https://github.com/HaughtCodeworks/cfp-app. However, this fork is currently marked as "experimental" and if you're upgrading from an older version, you'll find that the migrations do not run cleanly.

You might be interested in a fork of that fork here: https://github.com/rubyberlin/cfp-app. It's already powered one conference in the UK early in the year and is still under pretty active development.

**Comment by mghaught** [comment]
We've merged back the long-lived experimental branch.
