### ISSUE TITLE
Consider use dependabot

### ISSUE THREAD

**Issue by lucianosousa** [rubycentral/cfp-app#141]
I've seen couple PR's updating some gems, would be nice if people focus more in system logic than spending time doing it.
I would like to suggest use of https://dependabot.com to make it run automatically.
I'm not a member of dependabot project but I've been using it for a while and it's really relevant to all of these projects

Let me know what you think about. :wave:

**Comment by barrettclark** [comment]
Dependabot generated PR: https://github.com/rubycentral/cfp-app/pull/149
