### ISSUE TITLE
Proposal diffs

### ISSUE THREAD

**Issue by olivierlacan** [rubycentral/cfp-app#23]
I regularly receive notifications that a proposal was updated by the speaker but it's near-impossible to tell what (if anything) they changed on the proposal.

Some sort of diff view would be useful to get an idea of the evolution of the proposal.

I've used something like paper_trail to keep iterations of an object's text fields and diff each version with the previous one: https://github.com/airblade/paper_trail

**Comment by barrettclark** [comment]
Related to https://github.com/rubycentral/cfp-app/issues/38

**Comment by barrettclark** [comment]
https://github.com/rubycentral/cfp-app/pull/198 adds the Paperclip gem, laying the foundation for this as a future update. I wanted to at least allow for the data to be there once I have a better idea on how to present it.
