### ISSUE TITLE
Events get saved with year "0015"

### ISSUE THREAD

**Issue by kevinburke** [rubycentral/cfp-app#32]
Steps to reproduce:

- Go through install steps
- check out 2015 branch
- try to create an event
- for any date field, select "March 20 2015" or any date in 2015
- observe the value "March 20 15" is saved in the text field
- observe the date is saved as "March 20, 0015" or 15 years A.D.

I cannot reproduce this on the master branch.

**Comment by mghaught** [comment]
Wow, that's wild.  I'll take a look!

**Comment by mghaught** [comment]
So I was never able to confirm back when you reported this. We're running fully on master now and I tried a date field and was unable to reproduce.  I don't know what caused this but it seems to be fixed.  I'm going to close this issue but please post a new one if you can reproduce on master.  Thanks!
