### ISSUE TITLE
Change "Save" button to "Send Proposal" to avoid whoopsies

### ISSUE THREAD

**Issue by olivierlacan** [rubycentral/cfp-app#33]
Dangerous when misunderstood:
![image](https://cloud.githubusercontent.com/assets/65950/5961350/5f6b791a-a7dc-11e4-9156-d13cb376ba76.png)

See: https://twitter.com/aquaranto/status/560831291654815745
> TIL that 'Save' on the @railsconf CFP page actually means 'Submit'. @sarahmei is there anything I can do? Resubmit?

I think `Send Proposal` is the best action description for this button.

**Comment by mghaught** [comment]
I've patched and deployed this.
