### ISSUE TITLE
Show talk proposal title in <title> tag

### ISSUE THREAD

**Issue by olivierlacan** [rubycentral/cfp-app#34]
When reviewing applications this is what my tabs look like in Chrome:
![image](https://cloud.githubusercontent.com/assets/65950/6178258/715de266-b30d-11e4-8ef2-24c78da0d0ad.png)

Would be far easier to tell applications apart if the proposal review pages used the proposal title as the `<title>` tag.

**Comment by mghaught** [comment]
done!
