### ISSUE TITLE
Character counter issue on Abstract field?

### ISSUE THREAD

**Issue by olivierlacan** [rubycentral/cfp-app#35]
This proposal specifically complained that a 587-character abstract tripped the 600-character limit:
![image](https://cloud.githubusercontent.com/assets/65950/6178553/5d620226-b310-11e4-8670-c9ab90551ee2.png)

**Comment by searls** [comment]
LOL I have exactly the same issue. An abstract I want to submit for RubyConf 2015 is 597 chars and is being rejected

**Comment by evanphx** [comment]
I fixed that here: https://github.com/rubycentral/cfp-app/commit/bc5d3e8b345fbe47731f9375cfefc8194a9535a4

The other reason y'all are thinking that it's off is that it counts newlines, not just printed characters. So the one that was 587 probably had 13 newlines in it too.
