### ISSUE TITLE
Include a ratings guide in the app

### ISSUE THREAD

**Issue by olivierlacan** [rubycentral/cfp-app#36]
I'm sure ratings are very conference-specific and that these guidelines might change but it still seems like this guidance should be present in the app and not simply something we remind reviewers occasionally about: 

![image](https://cloud.githubusercontent.com/assets/65950/6178796/ceb0389c-b312-11e4-80da-81fea7a3b831.png)

/cc @mghaught

**Comment by mghaught** [comment]
Added to latest release!
