### ISSUE TITLE
Give reviewers the ability to withdraw a rating

### ISSUE THREAD

**Issue by olivierlacan** [rubycentral/cfp-app#37]
I've discovered a conflict of interest/bias on a proposal I'm reviewing after I've rated it but sadly there's no way for me to remove my rating. 

![image](https://cloud.githubusercontent.com/assets/65950/6197815/09ac9b72-b3ed-11e4-9a1b-f3a3e4bb6bf6.png)

**Comment by mghaught** [comment]
For now, just change your rating to fall in line with the existing averages.

**Comment by olivierlacan** [comment]
Ok.

**Comment by mghaught** [comment]
Fixed.
