### ISSUE TITLE
Notification history for a proposal

### ISSUE THREAD

**Issue by olivierlacan** [rubycentral/cfp-app#38]
Notifications are partially useful for the latest activity but it's often interesting to look at how much a proposal has improved since you last review it and/or gave suggestions to the the speaker.

Would be nice to be able to access a simple list of the history of the proposal from the anonymous proposal review page.

**Comment by mghaught** [comment]
So I'm cleaning up issues and I wanted to ask more about this one.  Are you wanting to see a diff history of the proposal change by change or just a list of the what types of changes (updated title, updated abstract) were done with date information?

**Comment by olivierlacan** [comment]
I think both would be nice but the diff would obviously be more useful to reviewers who get notified about changes.

**Comment by mghaught** [comment]
Understood.  We'll see what we can fit into this next update.  Thanks!

**Comment by barrettclark** [comment]
Closing this in favor of #23
