### ISSUE TITLE
Email notifications for conversations on commented proposals

### ISSUE THREAD

**Issue by olivierlacan** [rubycentral/cfp-app#42]
I found myself checking the CFP app for notifications on the proposals in my track to make sure the speakers weren't asking me important questions and somehow the fact that looking at the quick-view version of the notifications in the navigation doesn't mark these notifications as viewed convinced me that I had already seen them before. 

Having a small relative time aligned right on the quick view for notifications would probably help a bit but better yet, receiving emails notifications for conversations I'm clearly involved in (having commented) would be ideal. A simple toggle on the profile would be a good way to disable this for people who don't want to receive email notifications.

**Comment by mghaught** [comment]
This was implemented after RailsConf 2015
