### ISSUE TITLE
Speaker does not get confirmation button to finalize

### ISSUE THREAD

**Issue by bilsch** [rubycentral/cfp-app#53]
We are wrapping up the CFP for our conference. We found what I believe is missing functionality or a bug in existing functionality.

The speakers do not get a confirmation button to click once in the app. As an organizer I have a confirm for speaker button and that does work.

I updated to latest master - the sha is a8ebc992730ab0368ef10aec33aceb39429448fd

**Comment by mghaught** [comment]
The confirmation process was designed through email notices.  In the confirmation email they'll have a special link which will take them to a confirmation page.  It does seem like a good idea to give them a confirmation button on the proposal screen as well.  Are folks not getting the confirmation emails?

**Comment by bilsch** [comment]
I had a config issue which resulted in bad urls in the email. We ended up confirming via email corresp. I fixed it but only after having finalized everything ;)

**Comment by mghaught** [comment]
Ah, great.  Do you think we need to update the doc to help others avoid that?  Adding an issue for a confirm button on the proposal page seems wise too.

**Comment by bilsch** [comment]
I think the misconfig was more my fault than anything. I can create an issue to add a confim button to the proposal page for the user
