### ISSUE TITLE
Links in confirmation email broken

### ISSUE THREAD

**Issue by dblock** [rubycentral/cfp-app#55]
<img width="1189" alt="screenshot 2015-10-01 07 12 18" src="https://cloud.githubusercontent.com/assets/542335/10219299/c612a176-680b-11e5-8e78-b696be255227.png">

These links go to the wrong place, should be http://nycrb-cfp.herokuapp.com/events/nyc-rb-october/proposals/f67565cef2/confirm.

**Comment by mghaught** [comment]
This looks like a MAIL_HOST env variable issue.  Both our production and test environments show the correct link in confirmation emails.

**Comment by dblock** [comment]
But MAIL_HOST and the application host are two different things, this one should *not* be the mail host. Either way @nateberkopec should check on the NYC.rb deployment I suppose.

**Comment by nateberkopec** [comment]
Oh hey @dblock - it was an issue with my setting of the MAIL_HOST config var.

**Comment by dblock** [comment]
:+1:

**Comment by mghaught** [comment]
Yeah, the env variable name may not be the best but it's used by the mailer code to determine the host domain for any links sent out.
