### ISSUE TITLE
Back to proposal link broken

### ISSUE THREAD

**Issue by dblock** [rubycentral/cfp-app#56]
On http://nycrb-cfp.herokuapp.com/events/nyc-rb-october/proposals/f67565cef2/confirm

<img width="809" alt="screenshot 2015-10-01 07 13 13" src="https://cloud.githubusercontent.com/assets/542335/10219320/e901eade-680b-11e5-850a-5fdb3ce5f705.png">

Back to proposal goes to http://nycrb-cfp.herokuapp.com/organizer/events/1/proposals/f67565cef2, which is a 404.

**Comment by mghaught** [comment]
Did you delete the proposal? Was this already confirmed and you visited it again?

**Comment by mghaught** [comment]
Fixed.

**Comment by dblock** [comment]
Proposal wasn't deleted, just pressed the back button.
