### ISSUE TITLE
HTML markup in proposal summary

### ISSUE THREAD

**Issue by dblock** [rubycentral/cfp-app#57]
<img width="684" alt="screenshot 2015-10-01 07 14 26" src="https://cloud.githubusercontent.com/assets/542335/10219337/145ab3f0-680c-11e5-8e8b-879a6401dfb2.png">

That <p> should not be there.

**Comment by mghaught** [comment]
Did you put html tags in your proposal and that's why there's a <p> tag there?

**Comment by dblock** [comment]
I certainly didn't when I submitted this proposal.
