### ISSUE TITLE
Link to the event on the confirmation page is broken

### ISSUE THREAD

**Issue by dblock** [rubycentral/cfp-app#58]
I saw a link tot he event (on meetup) on the proposal confirmation page. Can't get to it now since the proposal was confirmed. That link is broken.

**Comment by mghaught** [comment]
Tell me more about this one.  Someone posted the confirmation link to a meetup site?  Why would they do that?

**Comment by dblock** [comment]
Sorry just seeing this @mghaught. The link was *to* meetup from the proposal received confirmation page on cfp-app, not the other way around.
