### ISSUE TITLE
Cfp app crashed in Heroku with error code H10

### ISSUE THREAD

**Issue by jcapde87** [rubycentral/cfp-app#81]
Hi, 

We've deployed the cfp-app in heroku couple of months ago and It has been running amazingly up till today, but it has just crashed with error code H10.  Heroku logs were not very explicit and they simply said  (at=error code=H10 desc="App crashed"). They also said "Don't know how to build task 'jobs:work'" and recommended to start the task manually with option --trace to see the full trace. 
Given that this is in production, we simply restarted the app and wake up normally. We would like now to figure out what happened, but it is hard to reproduce the error. Have you encountered this problem or do you have any idea about it?

Many thanks,
Joan

**Comment by mghaught** [comment]
I have not seen this sort of issue with our app.  We've been running the cfp-app for over three years now on Heroku and I don't recall having many H10s.  Can you reach out to heroku support to try and find out more about what is crashing the app?
